Multiple modification to nagios plugins.

diff --git a/check_sensors_ikus b/check_sensors_ikus
--- a/check_sensors_ikus
+++ b/check_sensors_ikus
@@ -1,14 +1,18 @@
 #! /bin/bash
 
 ###
-# Nagios plugin skeleton
-# http://nagiosplug.sourceforge.net/developer-guidelines.html
+# Check hardware sensor using `ipmitool` or `freeipmi`.
 #
-# Check hardware sensor using sensors command line provided by lm-sensors
+# Required the following sudoers
+#
+#     nagios ALL=(ALL) NOPASSWD: /usr/bin/ipmitool sensor
+# OR
+#     nagios ALL=(ALL) NOPASSWD: /usr/sbin/ipmi-sensors
+#     nagios ALL=(ALL) NOPASSWD: /usr/sbin/ipmi-dcmi
 #
 # @AUTHOR: Patrik Dufresne (http://patrikdufresne.com)
-# Copyright 2012 Patrik Dufresne
-# Last modified 2012-07-31
+# Copyright 2015 Patrik Dufresne
+# Last modified 2015-02-22
 # Please send all comments, suggestions, bugs and patches to (info AT patrikdufresne DOT com)
 #
 # This program is free software: you can redistribute it and/or modify
@@ -39,22 +43,20 @@ SERVICE="SENSOR"
 # Replacement for the exit function, will cleanup any tempfiles or such
 # before exiting.
 function cleanup {
-	exit $1
+    exit $1
 }
 
 declare -rx PROGNAME=${0##*/}
-#declare -rx PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
-#declare -rx PROGPATH=`dirname "$0"`
 declare -rx PROGPATH=${0%/*}/
 
 if [ -r "${PROGPATH}utils.sh" ] ; then
-	source "${PROGPATH}utils.sh"
+    source "${PROGPATH}utils.sh"
 else
-	echo "Can't find utils.sh. This plugin needs to be run from the same directory as utils.sh which is most likely something like /usr/lib/nagios/plugins or /usr/lib64/nagios/plugins"
-	printf "Currently being run from %s\n" "$PROGPATH"
-	# Since we couldn't define STATE_UNKNOWN since reading utils.sh
+    echo "Can't find utils.sh. This plugin needs to be run from the same directory as utils.sh which is most likely something like /usr/lib/nagios/plugins or /usr/lib64/nagios/plugins"
+    printf "Currently being run from %s\n" "$PROGPATH"
+    # Since we couldn't define STATE_UNKNOWN since reading utils.sh
     # failed, we use 3 here but everywhere else after this use cleanup $STATE
-	cleanup 3
+    cleanup 3
 fi
 
 # Set STATE to UNKNOWN as soon as we can (right after reading in util.sh
@@ -64,24 +66,22 @@ STATE=$STATE_UNKNOWN
 # make sure that any external commands are installed, in the PATH and
 # executable. The following example is stupid because of course date is
 # installed but it's the only command this trivial check really uses
+IPMITOOL=/usr/bin/ipmitool
+FREEIPMI=/usr/sbin/ipmi-sensors
 SENSORS=/usr/bin/sensors
-if [ ! -x "$SENSORS" ] ; then
-	echo "The utility is not installed, in your path and executable. Exiting."
-	cleanup $STATE_UNKNOWN
+if [ ! -x "$IPMITOOL" -a ! -x "$FREEIPMI" -a ! -x "$SENSORS" ] ; then
+    echo "neither $IPMITOOL, $FREEIPMI or $SENSORS is installed, in your path and executable. Exiting."
+    cleanup $STATE_UNKNOWN
 fi
-
-# provide a quick one liner of how to use the program
-function usage {
-	printf " %s %s for Nagios - Usage %s -s <sensor name> \
--w <warning threshold> -c <critical threshold> \
-[-t timeout] [-v [-v [-v]]]\n" "$PROGNAME" "$VERSION" "$PROGNAME"
-	cleanup $STATE_UNKNOWN
-}
 
 # provide detailed explanations of the command line syntax
 function longhelp {
-	# put your long help here
-	printf "%s plugin version %s for Nagios by %s
+    printf " %s %s for Nagios - Usage %s [-s <sensor name> \
+-w <warning threshold> -c <critical threshold>] \
+[-t timeout] [-v [-v [-v]]]\n" "$PROGNAME" "$VERSION" "$PROGNAME"
+    cleanup $STATE_UNKNOWN
+    # put your long help here
+    printf "%s plugin version %s for Nagios by %s
   -h, --help          Display this message.
   -s, --sensor        Set the sensor to monitor
   -w, --warning=val   Set the warning percentage threshold.
@@ -92,12 +92,12 @@ function longhelp {
   -V, --version       Print version information.
   --range_help        Explain threshold ranges.
 " "$PROGNAME" "$VERSION" "$AUTHOR"
-	cleanup $STATE_UNKNOWN
+    cleanup $STATE_UNKNOWN
 }
 
 # explanatory function you probably want to keep
 function range_help {
-	printf "
+    printf "
 The format for ranges in Nagios can be confusing and it isn't always followed.
 
 [@]start[:[end]]
@@ -130,18 +130,14 @@ Formal Rules:
 
 More help at http://nagiosplug.sourceforge.net/developer-guidelines.html
 "
-	cleanup $STATE_UNKNOWN
+    cleanup $STATE_UNKNOWN
 }
-
-if [ $# -eq 0 ] ; then
-	usage
-fi
 
 # use getopt, trust me on this one. It's the easiest way
 getopt -T
 if [ $? -ne 4 ] ; then
-	printf "%s: getopt is in compatibility mode.\n" "$SCRIPT"
-	cleanup $STATE_UNKNOWN
+    printf "%s: getopt is in compatibility mode.\n" "$SCRIPT"
+    cleanup $STATE_UNKNOWN
 fi
 
 # Tell it which switches and longswitches you'll take and place a trailing
@@ -155,8 +151,13 @@ RESULT=`getopt --name "$SCRIPT" --options "-h,-V,-v,-c:,-w:,-t:,-s:" --longoptio
 # make the result of getopt your new argument list ($@)
 eval set -- "$RESULT"
 
-declare WARNING
-declare CRITICAL
+declare -i IDX=0
+declare -a WARNING
+declare -a CRITICAL
+declare -a SENSOR
+declare -a SENSOR_NAME
+declare -a SENSOR_VALUE
+declare -a SENSOR_UNIT
 # all scripts should have a mechanism to terminate themselves if they are
 # running for too long. Scripts you might think of as innocuous could end
 # up waiting forever on I/O, especially if a disk is failing
@@ -165,57 +166,94 @@ declare -i TIMELIMIT=15
 declare -i VERBOSITY=0
 
 while [ $# -gt 0 ] ; do
-	case "$1" in
-		-h | --help)
-			longhelp;;
-		-V | --version)
-			print_revision "$PROGNAME" "$VERSION"
-			cleanup $STATE;;
-		-v | --verbose)
-			VERBOSITY=$(($VERBOSITY + 1));;
-		--verbosity)
-			shift
-			VERBOSITY=$1;;
-		-w | --warning)
-			shift
-			WARNING=$1;;
-		-c | --critical)
-			shift
-			CRITICAL=$1;;
-		-t | --timeout)
-			shift
-			TIMELIMIT=$1;;
-		-s | --sensor)
-			shift
-			SENSOR=$1;;
-		--)
-			shift
-			break;;
-		*)
-			echo "Option $1 not supported. Ignored." >&2;;
-	esac
-	shift
+    case "$1" in
+        -h | --help)
+            longhelp;;
+        -V | --version)
+            print_revision "$PROGNAME" "$VERSION"
+            cleanup $STATE;;
+        -v | --verbose)
+            VERBOSITY=$(($VERBOSITY + 1));;
+        --verbosity)
+            shift
+            VERBOSITY=$1;;
+        -w | --warning)
+            shift
+            WARNING[IDX-1]=$1;;
+        -c | --critical)
+            shift
+            CRITICAL[IDX-1]=$1;;
+        -t | --timeout)
+            shift
+            TIMELIMIT=$1;;
+        -s | --sensor)
+            shift
+            SENSOR[IDX]=$1
+            IDX=$(( $IDX + 1 ))
+            ;;
+        --)
+            shift
+            break;;
+        *)
+            echo "Option $1 not supported. Ignored." >&2;;
+    esac
+    shift
 done
 
-#Verbosity level	Type of output
-#0			Single line, minimal output. Summary
-#1			Single line, additional information (eg list processes that fail)
-#2			Multi line, configuration debug output (eg ps command used)
-#3			Lots of detail for plugin problem diagnosis
+#Verbosity level    Type of output
+#0            Single line, minimal output. Summary
+#1            Single line, additional information (eg list processes that fail)
+#2            Multi line, configuration debug output (eg ps command used)
+#3            Lots of detail for plugin problem diagnosis
 if [ $VERBOSITY -gt 2 ] ; then
-	shopt -o -s xtrace
+    shopt -o -s xtrace
 fi
+
+# Check that the thresholds provided are valid strings
+for W in ${WARNING[@]}; do
+    if [ ! -z "$W" ]; then
+        FORMAT=`echo "$W" | grep -c '^@\?\([0-9]\+:[0-9]*\|[0-9]\+\)$'`
+        if [ $FORMAT -lt 1 ] ; then
+            echo "Please check the format of your warning thresholds: $W"
+            range_help
+        fi
+    fi
+done
+for C in ${CRITICAL[@]}; do
+    if [ ! -z "$C" ]; then
+        FORMAT=`echo "$C" | grep -c '^@\?\([0-9]\+:[0-9]*\|[0-9]\+\)$'`
+        if [ $FORMAT -lt 1 ] ; then
+            echo "Please check the format of your critical thresholds: $C"
+            range_help
+        fi
+    fi
+done
+
+function normalize_unit {
+    if [ "$1" == "degreesC" ]; then
+        echo "C"
+    elif [ "$1" == "Volts" ]; then
+        echo "V"
+    elif [ "$1" == "discrete" ]; then
+        echo ""
+    elif [ "$1" == "discrete" ]; then
+        echo ""
+    elif [ "$1" == "Watts" ]; then
+        echo "watts"
+    else
+        echo "$1"
+    fi
+}
 
 # what needs to happen in the event of a timeout
 function timeout {
-	echo "UNKNOWN - script timed out after $TIMELIMIT seconds."
-	cleanup $STATE_UNKNOWN
+    echo "UNKNOWN - script timed out after $TIMELIMIT seconds."
+    cleanup $STATE_UNKNOWN
 }
-
 # since we've processed the options which potentially set the timeout limit,
 # we can setup a timeout trap now
 trap timeout USR1
-	# what we're doing here sending a USR1 signal back to this process which
+    # what we're doing here sending a USR1 signal back to this process which
     # we just set a trap to catch and run the timeout function the syntax of
     # this is important and very odd - if you know of a better way to do this, 
     # please email me what we're doing is starting another process in the
@@ -226,119 +264,190 @@ trap timeout USR1
     # this is sending USR1 to another instance of this script that just happens
     # to get assigned the same process ID it should be reasonable to assume
     # that your Nagios check interval is greater than the specified timeout
-	# still, if you havea better idea...
-	( sleep $TIMELIMIT; if [ `pgrep -U $USER -f "$SCRIPT" | grep -c ^$$$` -gt 0 ] ; then kill -USR1 $$ ; fi; ) </dev/null &>/dev/null &
+    # still, if you havea better idea...
+    ( sleep $TIMELIMIT; if [ `pgrep -U $USER -f "$SCRIPT" | grep -c ^$$$` -gt 0 ] ; then kill -USR1 $$ ; fi; ) </dev/null &>/dev/null &
 
-    # Check that sensor is provided
-    if [ -z "$SENSOR" ] ; then
-        usage
+    # If IPMITOOL is available, use it.
+    if [ -x "$IPMITOOL" ]; then
+        # Parse raw data
+        # FAN 1            | 1510.000   | RPM        | ok    | 400.000   | 585.000   | 770.000   | 29260.000 | 29815.000 | 30370.000
+        DATA=$(sudo -n "$IPMITOOL" sensor)
+        if [ $? -gt 0 ]; then
+            printf "UNKNOWN - Fail to execute $IPMITOOL. Check if sudo rule exists.\n"
+            cleanup $STATE_UNKNOWN
+        fi
+        # Capture data for each line.
+        IDX=0
+        while read LINE; do
+            SENSOR_NAME[$IDX]=$(echo $LINE | cut -d '|' -f 1 | sed -e 's/[ \t]*//g')
+            SENSOR_VALUE[$IDX]=$(echo $LINE | cut -d '|' -f 2 | sed -e 's/[ \t]*//g')
+            SENSOR_UNIT[$IDX]=$(echo $LINE | cut -d '|' -f 3 | sed -e 's/[ \t]*//g')
+            SENSOR_UNIT[$IDX]=$(normalize_unit "${SENSOR_UNIT[$IDX]}")
+            IDX=$(( $IDX + 1 ))
+        done <<< "$DATA"
+    elif [ -x "$FREEIPMI" ]; then
+        # Parse raw data
+        # ID   | Name            | Reading    | Units | Event
+        # 4    | CPU Temp        | 25.00      | C     | 'OK'
+        DATA=$(sudo -n "$FREEIPMI" --no-header-output --no-sensor-type-output --ignore-not-available-sensors)
+        if [ $? -gt 0 ]; then
+            printf "UNKNOWN - Fail to execute $FREEIPMI. Check if sudo rule exists.\n"
+            cleanup $STATE_UNKNOWN
+        fi
+        # Capture data for each line.
+        IDX=0
+        while read LINE; do
+            SENSOR_NAME[$IDX]=$(echo "$LINE" | cut -d '|' -f 2 | sed -e 's/[ \t]*//g')
+            SENSOR_VALUE[$IDX]=$(echo "$LINE" | cut -d '|' -f 3 | sed -e 's/[ \t]*//g')
+            SENSOR_UNIT[$IDX]=$(echo "$LINE" | cut -d '|' -f 4 | sed -e 's/[ \t]*//g')
+            SENSOR_UNIT[$IDX]=$(normalize_unit "${SENSOR_UNIT[$IDX]}")
+            IDX=$(( $IDX + 1 ))
+        done <<< "$DATA"
+        # Try to capture power stats
+        # Current Power : 62 Watts
+        DATA=$(sudo /usr/sbin/ipmi-dcmi --get-system-power-statistics | grep 'Power' | egrep -o "^[^:]*:\s*[+\-]?[0-9,\.]+\s?[^ ]*")
+        if [ $? -eq 0 ]; then
+            while read LINE; do
+                SENSOR_NAME[$IDX]=$(echo $LINE | cut -d ':' -f 1 | cut -d ' ' -f 1-2 | sed -e 's/[ \t]*//g')
+                SENSOR_VALUE[$IDX]=$(echo $LINE | cut -d ':' -f 2 | sed -e 's/[ \t]*//g' -e 's/[^0-9,\.\-]//g')
+                SENSOR_UNIT[$IDX]=$(echo $LINE | cut -d ':' -f 2 | sed -e 's/[ \t]*//g' -e 's/[0-9,\.\-+°]*//g')
+                SENSOR_UNIT[$IDX]=$(normalize_unit "${SENSOR_UNIT[$IDX]}")
+                IDX=$(( $IDX + 1 ))
+            done <<< "$DATA"
+        fi
+    elif [ -x "$SENSORS" ]; then
+        # Parse raw data
+        # Vcore:         +0.78 V
+        DATA=$("$SENSORS" | egrep -o "^[^:]*:\s*[+\-]?[0-9,\.]+\s?[^ ]*")
+        if [ $? -gt 0 ]; then
+            printf "UNKNOWN - Fail to execute $SENSORS.\n"
+            cleanup $STATE_UNKNOWN
+        fi
+        # Capture data for each line.
+        IDX=0
+        while read LINE; do
+            SENSOR_NAME[$IDX]=$(echo $LINE | cut -d ':' -f 1 | sed -e 's/[ \t]*//g')
+            SENSOR_VALUE[$IDX]=$(echo $LINE | cut -d ':' -f 2 | sed -e 's/[ \t]*//g' -e 's/[^0-9,\.\-]//g')
+            SENSOR_UNIT[$IDX]=$(echo $LINE | cut -d ':' -f 2 | sed -e 's/[ \t]*//g' -e 's/[0-9,\.\-+°]*//g')
+            SENSOR_UNIT[$IDX]=$(normalize_unit "${SENSOR_UNIT[$IDX]}")
+            IDX=$(( $IDX + 1 ))
+        done <<< "$DATA"
     fi
 
-	# Check that the thresholds provided are valid strings
-	if [ -z "$WARNING" -o -z "$CRITICAL" ] ; then
-		range_help
-	else
-		# positive values only
-		WARNFORMAT=`echo "$WARNING" | grep -c '^@\?\([0-9]\+:[0-9]*\|[0-9]\+\)$'`
-		CRITFORMAT=`echo "$CRITICAL" | grep -c '^@\?\([0-9]\+:[0-9]*\|[0-9]\+\)$'`
-
-		OK=$(( $WARNFORMAT + $CRITFORMAT ))
-		if [ $OK -lt 2 ] ; then
-			echo "Please check the format of your warning and critical thresholds."
-			range_help
-		fi
-	fi
-
-	# Get the sensor's value
-    LINE=`$SENSORS | grep "$SENSOR" | head -n 1`
-    if [[ -z "$LINE" ]]; then
-	    #Given sensor doesn't exists
-	    printf "UNKNOWN - Given sensors $SENSOR doesn't exists.\n"
-        cleanup $STATE_UNKNOWN
-    fi
-    VALUE=`echo $LINE | sed 's/.*:[ \t]\{1,\}[\+\-]\{0,1\}\([0-9]\{1,\}\)[0-9\.]\{0,\}.*/\1/'`
-    VALUE_UNIT=$(echo $LINE | sed 's/.*:[ \t]\{1,\}[\+\-]\{0,1\}\([0-9]\{1,\}[ °a-ZA-Z0-9\.]\{0,\}\).*/\1/')
-    SENSOR=$(echo $LINE | sed 's/\(.*\):.*/\1/')
-
-	# Once we're done doing work that could take any real time, we can end the
+    # Once we're done doing work that could take any real time, we can end the
     # trap because from here on out it's just comparisons and string
     # concatenation
 trap - USR1
 
 function check_value {
-	# If the range starts with an @, alert if value is inside the range,
+    if [ -z "$1" ]; then
+        return 0
+    fi
+    # If the range starts with an @, alert if value is inside the range,
     # otherwise alert if value is outside of range.
-	INSIDE=`echo "$1" | grep -c '^@'`
-	RANGE=`echo "$1" | sed 's/^@//'`
+    INSIDE=`echo "$1" | grep -c '^@'`
+    RANGE=`echo "$1" | sed 's/^@//'`
 
-	# Start is anything left of the colon or 0.
+    # Start is anything left of the colon or 0.
     # End is anything right of the colon or the whole string if there's no
     # colon or infinity if there is a colon and nothing to the right of it
 
-	# is there a colon?
-	PARTS=`echo "$RANGE" | awk -F : '{ print NF }'`
-	if [ $PARTS -gt 1 ] ; then
-		START=${RANGE%%:*}
-		END=${RANGE##*:}
-	else
-		START=0
-		END=$RANGE
-	fi
+    # is there a colon?
+    PARTS=`echo "$RANGE" | awk -F : '{ print NF }'`
+    if [ $PARTS -gt 1 ] ; then
+        START=${RANGE%%:*}
+        END=${RANGE##*:}
+    else
+        START=0
+        END=$RANGE
+    fi
 
-	# 4. to specify negative infinity, use "~"
-	if [ "$START" == "~" ] ; then
-		START=-999999999
-	fi
+    # 4. to specify negative infinity, use "~"
+    if [ "$START" == "~" ] ; then
+        START=-999999999
+    fi
 
-	if [ -z "$END" ] ; then
-		END=999999999
-	fi
+    if [ -z "$END" ] ; then
+        END=999999999
+    fi
 
-	if [ $START -gt $END ] ; then
-		echo "In threshold START:END, START must be less than or equal to END"
-		range_help
-	fi
+    if [ $START -gt $END ] ; then
+        echo "In threshold START:END, START must be less than or equal to END"
+        range_help
+    fi
 
-	# if the range starts with an @, alert if value is inside the range, otherwise alert if value is outside of range
-	# all ranges are inclusive of endpoints so we use less than or equal on the inside and just less than on the outside
-	if [ "$INSIDE" -gt 0 ] ; then
-		if [ "$START" -le "$2" -a "$2" -le "$END" ] ; then
-			return 1
-		fi
-	else
-		if [ "$2" -lt "$START" -o "$END" -lt "$2" ] ; then
-			return 1
-		fi
-	fi
+    # if the range starts with an @, alert if value is inside the range, otherwise alert if value is outside of range
+    # all ranges are inclusive of endpoints so we use less than or equal on the inside and just less than on the outside
+    if [ "$INSIDE" -gt 0 ] ; then
+        if [ $(echo "$START <= $2 && $2 <= $END" | bc) -eq 1 ] ; then
+          return 1
+        fi
+    elif [ $(echo "$2 < $START || $END < $2" | bc) -eq 1 ] ; then
+        return 1
+    fi
 
-	return 0
+    return 0
 }
 
-# check conditions - yes this is ugly, blame BASH. If you want to blame me, please provide a cleaner way that is as fast or faster
-check_value "$CRITICAL" "$VALUE"
-if [ $? -gt 0 ] ; then
-	STATE=$STATE_CRITICAL
-else
-	check_value "$WARNING" "$VALUE"
-	if [ $? -gt 0 ] ; then
-		STATE=$STATE_WARNING
-	else
-		STATE=$STATE_OK
-	fi
-fi
+# check conditions - yes this is ugly, blame BASH. 
+# If you want to blame me, please provide a cleaner way that is as fast or faster
+IDX=0
+DESC=""
+STATE=$STATE_OK
+while [ "x${SENSOR[IDX]}" != "x" ]; do
+    IDX2=0
+    VALUE=""
+    while [ "x${SENSOR_NAME[IDX2]}" != "x" -a "${SENSOR_NAME[IDX2]}" != "${SENSOR[IDX]}" ]; do
+        IDX2=$(( $IDX2 + 1 ))
+    done
+    if [ "${SENSOR_NAME[IDX2]}" != "${SENSOR[IDX]}" ]; then
+        printf "UNKNOWN - Given sensors ${SENSOR[IDX]} doesn't exists.\n"
+        cleanup $STATE_UNKNOWN
+    fi
+    VALUE="${SENSOR_VALUE[IDX2]}"
+    check_value "${CRITICAL[IDX]}" "$VALUE"
+    if [ $? -gt 0 ] ; then
+        STATE=$STATE_CRITICAL
+        if [ ! -z "$PERF" ]; then DESC="$DESC, "; fi
+        DESC="$DESC${SENSOR_NAME[IDX2]}: ${SENSOR_VALUE[IDX2]}${SENSOR_UNIT[IDX2]}"
+    fi
+    if [ ! $STATE -eq $STATE_CRITICAL ]; then
+        check_value "${WARNING[IDX]}" "$VALUE"
+        if [ $? -gt 0 ] ; then
+            STATE=$STATE_WARNING
+            if [ ! -z "$PERF" ]; then DESC="$DESC, "; fi
+            DESC="$DESC${SENSOR_NAME[IDX2]}: ${SENSOR_VALUE[IDX2]}${SENSOR_UNIT[IDX2]}"
+        fi
+    fi
+    IDX=$(( $IDX + 1 ))
+done
 
 # STATE - Message | 'label'=value[unit of measure];[warn];[crit];[min];[max]
-OUT="$SENSOR $VALUE_UNIT | $SENSOR=${VALUE};$WARNING;$CRITICAL"
+
+PERF=""
+IDX=0
+while [ "x${SENSOR_NAME[IDX]}" != "x" ]; do
+    # Skip N/A values.
+    if [ "${SENSOR_VALUE[IDX]}" != "N/A" -a "${SENSOR_VALUE[IDX]}" != "na" ]; then
+        if [ ! -z "$PERF" ]; then
+            PERF="$PERF "
+        fi
+        PERF="$PERF${SENSOR_NAME[IDX]}=${SENSOR_VALUE[IDX]}${SENSOR_UNIT[IDX]}"
+    fi
+    IDX=$(( $IDX + 1 ))
+done
+
+OUT="$SENSOR $VALUE $VALUE_UNIT | $SENSOR=${VALUE};$WARNING;$CRITICAL"
 
 case $STATE in
-	$STATE_OK)
-		printf "%s OK - %s\n" "$SERVICE" "$OUT";;
-	$STATE_WARNING)
-		printf "%s WARNING - %s\n" "$SERVICE" "$OUT";;
-	$STATE_CRITICAL)
-		printf "%s CRITICAL - %s\n" "$SERVICE" "$OUT";;
-	$STATE_UNKNOWN)
-		printf "%s UNKNOWN - %s\n" "$SERVICE" "$OUT";;
+    $STATE_OK)
+        printf "%s OK - %s\n" "$SERVICE" "$DESC | $PERF";;
+    $STATE_WARNING)
+        printf "%s WARNING - %s\n" "$SERVICE" "$DESC | $PERF";;
+    $STATE_CRITICAL)
+        printf "%s CRITICAL - %s\n" "$SERVICE" "$DESC | $PERF";;
+    $STATE_UNKNOWN)
+        printf "%s UNKNOWN - %s\n" "$SERVICE" "$DESC | $PERF";;
 esac
 
 cleanup $STATE
